version: "3"
services:
  w2g-front:
    image: nifr3d/w2g-front:latest
    ports:
      - "80:80"
    restart: unless-stopped
  w2g-back:
    image: nifr3d/w2g-back:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - /home/fred/videos:/app/videos
    environment:
      VIDEO_DIR: /app/videos
    restart: unless-stopped
